syntax = "proto3";
package BlueProtobuf;

option csharp_namespace = "ACT_Plugin.BlueProtobuf";

message AoiSyncDelta {
	int64 Uuid = 1;
	AttrCollection Attrs = 2;
	TempAttrCollection TempAttrs = 3;
	EventDataList EventDataList = 4;
	BulletEvent BulletEvent = 5;
	ActorBodyPartInfos BodyPartInfos = 6;
	SkillEffect SkillEffects = 7;
	SeqPassiveSkillInfo PassiveSkillInfos = 8;
	SeqPassiveSkillEndInfo PassiveSkillEndInfos = 9;
}

message SyncContainerDirtyData {
	BufferStream VData = 1;
}

message BufferStream {
	bytes Buffer = 1;
}

message AttrCollection {
	int64 Uuid = 1;
	repeated Attr Attrs = 2;
	repeated MapAttr MapAttrs = 3;
}

message TempAttrCollection {
	repeated TempAttr Attrs = 1;
}

message Attr {
	int32 Id = 1;
	bytes RawData = 2;
}

message TempAttr {
	int32 Id = 1;
	int32 Value = 2;
}

message MapAttr {
	bool IsClear = 1;
	int32 Id = 2;
	repeated MapAttrValue Attrs = 3;
}

message MapAttrValue {
	bool IsRemove = 1;
	bytes Key = 2;
	bytes Value = 3;
}

message EventDataList {
	int64 Uuid = 1;
	repeated EventData events = 2;
}

message EventData {
	int32 EventType = 1;
	repeated int32 IntParams = 2;
	repeated int64 LongParams = 3;
	repeated float FloatParams = 4;
	repeated string StrParams = 5;
}

message BulletEvent {
	int64 Uuid = 1;
	int32 EnterStageId = 2;
}

message ActorBodyPartInfos {
	int64 Uuid = 1;
	repeated ActorBodyPartInfo Infos = 2;
}

message ActorBodyPartInfo {
	int32 PartId = 1;
	uint64 Hp = 2;
	uint64 MaxHp = 3;
	int32 State = 4;
	int32 FleshyId = 5;
}

message SkillEffect {
	int64 Uuid = 1;
	int64 TotalDamage = 3;
	repeated SyncDamageInfo Damages = 2;
}

message SyncDamageInfo {
	int32 DamageSource = 1;
	bool IsMiss = 2;
	bool IsCrit = 3;
	int32 Type = 4;
	int32 TypeFlag = 5;
	int64 Value = 6;
	int64 ActualValue = 7;
	int64 LuckyValue = 8;
	int64 HpLessenValue = 9;
	int64 ShieldLessenValue = 10;
	int64 AttackerUuid = 11;
	int32 OwnerId = 12;
	int32 OwnerLevel = 13;
	int32 OwnerStage = 14;
	int32 HitEventId = 15;
	bool IsNormal = 16;
	bool IsDead = 17;
	int32 Property = 18;
	Vector3 DamagePos = 19;
	int64 TopSummonerId = 21;
	Vector2 DamageWeight = 22;
	uint32 PassiveUuid = 23;
	bool IsRainbow = 24;
	int32 DamageMode = 25;
	repeated ClientHitPartInfo PartInfos = 20;
}

message Vector2 {
	float X = 1;
	float Y = 2;
}

message Vector3 {
	float X = 1;
	float Y = 2;
	float Z = 3;
}

message IntVec3 {
	int32 X = 1;
	int32 Y = 2;
	int32 Z = 3;
}

message ClientHitPartInfo {
	int32 PartId = 1;
	Vector3 DamagePos = 2;
	int64 DamageVal = 3;
}

message SeqPassiveSkillInfo {
	int64 ActorUuid = 1;
	repeated PassiveSkillInfo PassiveInfos = 2;
}

message PassiveSkillInfo {
	int32 Uuid = 1;
	int64 TargetUuid = 2;
	int64 StageBeginTime = 3;
	int64 BeginTime = 4;
	int32 StagePlayNum = 5;
	int32 SkillId = 6;
	int32 SkillLevel = 7;
	int32 SkillStage = 8;
}

message SeqPassiveSkillEndInfo {
	int64 ActorUuid = 1;
	repeated int64 Uuids = 2;
}

message SyncNearDeltaInfo {
	repeated AoiSyncDelta DeltaInfos = 1;
}

message SyncToMeDeltaInfo {
	AoiSyncToMeDelta DeltaInfo = 1;
}

message AoiSyncToMeDelta {
	AoiSyncDelta BaseDelta = 1;
	int64 Uuid = 5;
	repeated int64 SyncHateIds = 2;
	repeated SkillCD SyncSkillCDs = 3;
	repeated FightResCD FightResCDs = 4;
}

message SkillCD {
	int32 SkillLevelId = 1;
	int64 BeginTime = 2;
	int32 Duration = 3;
	int32 SkillCDType = 4;
	int32 ValidCDTime = 5;
}

message FightResCD {
	int32 ResId = 1;
	int64 BeginTime = 2;
	int32 Duration = 3;
	int32 ValidCDTime = 4;
}

message SyncContainerData {
	CharSerialize VData = 1;
}

message CharSerialize {
	int64 CharId = 1;
	CharBaseInfo CharBase = 2;
	SceneData SceneData = 3;
	SceneLuaData SceneLuaData = 4;
	PioneerData PioneerData = 5;
	//BuffDBInfo BuffInfo = 6;
	ItemPackage ItemPackage = 7;
	QuestDataList QuestList = 8;
	SettingData SettingData = 9;
	MiscInfo MiscInfo = 10;
	ExchangeItem ExchangeItems = 11;
	/*EquipList Equip = 12;
	EnergyItem EnergyItem = 13;
	MapData MapData = 14;
	DungeonList DungeonList = 15;*/
	UserFightAttr Attr = 16;
	/*FashionMgr Fashion = 17;
	ProfileList ProfileList = 18;
	PlayHelper Help = 19;
	CounterList CounterList = 20;
	PersonalObject PersonalObj = 21;
	RoleLevel RoleLevel = 22;
	Pivot Pivot = 23;
	TransferPoint TransferPoint = 24;
	PlanetMemory PlanetMemory = 25;
	SeasonTarget PlanetMemoryTarget = 26;
	RedDotData RedDot = 27;
	Resonance Resonance = 28;
	CutsState CutsState = 29;
	InvestigateList InvestigateList = 30;
	ParkourRecordList Records = 31;
	InteractionInfo Interaction = 32;
	SeasonQuestList SeasonQuestList = 33;
	RoleFace RoleFace = 34;
	MapBookInfoList MapBookList = 35;
	FunctionData FunctionData = 36;
	AntiAddictionInfo AntiInfo = 37;
	MonsterExploreList MonsterExploreList = 38;
	ShowPieceData ShowPieceData = 39;
	CollectionBook CollectionBook = 42;
	NotGetProceedAwardInfo NotGetProceedAwardTimes = 43;
	CookList Cooklist = 44;
	TimerRefreshDataList RefreshDataList = 45;
	ChallengeDungeonInfo ChallengeDungeonInfo = 46;
	SyncAwardData SyncAwardData = 47;
	SeasonAchievementList SeasonAchievementList = 48;
	SeasonRankList SeasonRankList = 49;
	SeasonCenter SeasonCenter = 50;
	PersonalZone PersonalZone = 51;
	SeasonMedalInfo SeasonMedalInfo = 52;
	CommunityHomeData CommunityHomeInfo = 53;
	SeasonActivation SeasonActivation = 54;
	Slot Slots = 55;
	MonsterHuntInfo MonsterHuntInfo = 56;
	Mod Mod = 57;
	WorldEventMap WorldEventMap = 58;
	FishSetting FishSetting = 59;
	FreightData FreightData = 60;*/
	ProfessionList ProfessionList = 61;
	/*TrialRoad TrialRoad = 62;
	GashaData GashaData = 63;
	ShopData ShopData = 64;
	PersonalWorldBossInfo PersonalWorldBossInfo = 65;
	CraftEnergyRecord CraftEnergy = 66;
	WeeklyTowerRecord WeeklyTower = 67;
	CutSceneInfos CutSceneInfos = 68;
	UserRecommendPlayData RecommendPlayData = 69;
	RideList RideList = 70;
	PayOrderList PayOrderList = 71;
	LifeProfession LifeProfession = 72;
	LifeProfessionWork LifeProfessionWork = 73;
	UserActivityList UserActivityList = 74;
	PlayerRecord PlayerRecord = 75;
	DropContainerInfo DropContainer = 76;
	MonthlyCard MonthlyCard = 77;
	FashionBenefit FashionBenefit = 78;
	ItemCurrency ItemCurrency = 79;
	PrivilegeEffectData PrivilegeEffectData = 80;
	Treasure Treasure = 81;
	UnlockEmojiData UnlockEmojiData = 82;
	PlayerOrderComtainerInfo PlayerOrderComtainerInfo = 83;
	PlayerBox PlayerBox = 84;
	LaunchPrivilegeData LaunchPrivilegeData = 85;
	BattlePassData BattlePassData = 86;
	RechargeData RechargeData = 87;
	LuckyValueMgr LuckyValueMgr = 88;
	HandbookData HandbookData = 89;
	MasterModeDungeonInfo MasterModeDungeonInfo = 90;
	StatisticsData StatisticsData = 91;
	CompensationStatistics CompenstionStatistics = 92;
	BubbleActData BubbleActData = 93;
	MailClaimedInfo MailClaimedInfo = 94;
	NewbieData NewbieData = 95;
	FightPoint FightPoint = 96;
	SignInfo Sign = 97;
	CharStatisticsData CharStatisticsData = 98;		*/
}

message CharBaseInfo {
	int64 CharId = 1;
	string AccountId = 2;
	int64 ShowId = 3;
	uint32 ServerId = 4;
	string Name = 5;
	EGender Gender = 6;
	bool IsDeleted = 7;
	bool IsForbid = 8;
	bool IsMute = 9;
	float X = 10;
	float Y = 11;
	float Z = 12;
	float Dir = 13;
	FaceData FaceData = 14;
	uint32 CardId = 15;
	int64 CreateTime = 16;
	int64 OnlineTime = 17;
	int64 OfflineTime = 18;
	ProfileInfo ProfileInfo = 19;
	CharTeam TeamInfo = 20;
	uint64 CharState = 21;
	int32 BodySize = 22;
	UserUnion UnionInfo = 23;
	AvatarInfo AvatarInfo = 25;
	uint64 TotalOnlineTime = 26;
	string OpenId = 27;
	int32 SdkType = 28;
	int32 Os = 29;
	int32 InitProfessionId = 31;
	uint64 LastCalTotalTime = 32;
	int32 AreaId = 33;
	string ClientVersion = 34;
	int32 FightPoint = 35;
	int64 SumSave = 36;
	string ClientResourceVersion = 37;
	int64 LastOfflineTime = 38;
	int32 DayAccDurTime = 39;
	int64 LastAccDurTimestamp = 40;
	int64 SaveSerial = 41;
	
	repeated int32 PersonalState = 24;
}

message ProfessionList {
	int32 CurProfessionId = 1;
}

message FaceData {
	
	float Height = 3;
	
	message FaceInfoDict {
		int32 k = 1;
		int32 value = 2;
	}
	message ColorInfoDict {
		int32 k = 1;
		IntVec3 value = 2;
	}
	repeated FaceInfoDict FaceInfo = 1;
	repeated ColorInfoDict ColorInfo = 2;
}

message ProfileInfo {
	int32 ProfileId = 1;
	string ProfileUrl = 2;
	string HalfBodyUrl = 3;
}

message CharTeam {
	int64 TeamId = 1;
	int64 LeaderId = 2;
	uint32 TeamTargetId = 3;
	uint32 TeamNum = 4;
	bool IsMatching = 6;
	int32 CharTeamVersion = 7;
	repeated int64 CharIds = 5;
	
	message TeamMemberDataDict {
		int64 k = 1;
		TeamMemData value = 2;
	}

	repeated TeamMemberDataDict TeamMemberData = 8;
}

message TeamMemData {
	int64 CharId = 1;
	uint32 EnterTime = 2;
	int32 CallStatus = 3;
	int32 TalentId = 4;
	int32 OnlineStatus = 5;
	int32 SceneId = 6;
	bool VoiceIsOpen = 7;
	int32 GroupId = 8;
	TeamMemberSocialData SocialData = 9;
}

message TeamMemberSocialData {
	BasicData BasicData = 1;
	AvatarInfo AvatarInfo = 2;
	FaceData FaceData = 3;
	ProfessionData ProfessionData = 4;
	EquipData EquipData = 5;
	FashionData FashionData = 6;
	UserSceneInfo UserSceneInfo = 7;
	UserAttrData UserAttrData = 8;
	PersonalZoneShow PersonalZone = 9;
}

message BasicData {
	
	int64 CharID = 1;
	int64 ShowId = 2;
	string Name = 3;
	int32 Gender = 4;
	int32 BodySize = 5;
	int32 Level = 6;
	int32 SceneId = 7;
	int64 OfflineTime = 9;
	string SceneGuid = 10;
	int64 CreateTime = 11;
	uint32 CurTalentPoolId = 12;
	uint32 BotAiId = 13;
	int32 RegisterChannel = 14;
	uint64 CharState = 15;
	int64 OnlineTime = 16;
	int64 SumSaveDiamond = 17;
	bool IsNewbie = 18;
	
	repeated int32 PersonalState = 8;
}

message AvatarInfo {
	int32 AvatarId = 1;
	PictureInfo Profile = 2;
	PictureInfo HalfBody = 3;
	int32 BusinessCardStyleId = 4;
	int32 AvatarFrameId = 5;
	
}

message PictureInfo {

	string Url = 1;
	PictureVerify Verify = 2;
	
}

message PictureVerify {

	uint32 Size = 1;
	uint32 ReviewStartTime = 2;
	int64 Version = 3;
	
}

message ProfessionData {

	int32 ProfessionId = 1;
	int32 WeaponSkin = 2;
	
}

message EquipData {
	repeated EquipNine EquipInfos = 1;
}

message EquipNine {

	int32 Slot = 1;
	int32 EquipID = 2;
	
}

message FashionData {
	repeated FashionInfo FashionInfos = 1;
}

message FashionInfo {
	
	int32 Slot = 1;
	int32 FashionId = 2;
	FashionColorInfo Colors = 3;
	
}

message FashionColorInfo {
	oneof fashioncolorinfo_oneof {
		int32 Id = 1;
	}

	message ColorInfoDict {
		int32 k = 1;
		IntVec3 value = 2;
	}

	message AttachmentColorInfoDict {
		int32 k = 1;
		IntVec3 value = 2;
	}

	repeated ColorInfoDict Colors = 2;
	repeated AttachmentColorInfoDict AttachmentColor = 3;
}

message UserSceneInfo {
	oneof usersceneinfo_oneof {
		int32 SceneId = 1;
		string SceneGuid = 2;
		int32 LineId = 3;
	}
}

message UserAttrData {
	oneof userattrdata_oneof {
		int32 State = 1;
		int64 FightPoint = 2;
	}
}

message PersonalZoneShow {
	message MedalsDict {
		int32 k = 1;
		int32 value = 2;		
	}

	repeated MedalsDict Medals = 1;
}

message UserUnion {
	oneof userunion_oneof {
		int64 UnionId = 1;
		uint64 NextJoinTime = 2;
		bool JoinFlag = 4;
		int64 ActiveAwardResetTime = 6;
		int64 ActiveLastRefreshTime = 9;
		uint64 LeaveTime = 11;
		UnionDanceHistory DanceRecord = 13;
		UserUnionHuntInfo UserUnionHuntInfo = 14;
	}

	message ReqUnionTimesDict {
		int64 k = 1;
		uint64 value = 2;
	}

	repeated ReqUnionTimesDict ReqUnionTimes = 3;
	repeated int64 CollectedIds = 5;
	repeated int32 ReceivedAwardIds = 7;
	repeated UnionHistoryActive HistoryActivePoints = 8;
	repeated int32 FinishDailyActiveIds = 10;
}

message UnionHistoryActive {
	oneof unionhistoryactive_oneof {
		int64 UnionId = 1;
		int64 ActivePoints  = 2;
	}
}

message UnionDanceHistory {
	oneof uniondancehistory_oneof {
		int64 DanceEndTime = 1;
		bool SentDanceAward = 2;
		bool DrawnDanceAward = 3;
	}
}

message UserUnionHuntInfo {
	oneof userunionhuntinfo_oneof {
		int32 HuntRank = 1;
	}
}

message SceneData {
	uint32 MapId = 1;
	uint32 ChannelId = 2;
	Position Pos = 3;
	int64 LevelUuid = 4;
	Position LevelPos = 5;
	uint32 LevelMapId = 6;
	uint32 LevelReviveId = 7;
	uint32 PlaneId = 9;
	uint32 SceneLayer = 10;
	bool CanSwitchLayer = 11;
	Position BeforeFallPos = 12;
	string SceneGuid = 13;
	string DungeonGuid = 14;
	uint32 LineId = 15;
	uint32 VisualLayerConfigId = 16;
	LastSceneData LastSceneData = 17;
	int32 SceneAreaId = 18;
	int32 LevelAreaId = 19;
	int32 BeforeFallSceneAreaId = 20;

	message RecordIdDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	repeated RecordIdDict RecordId = 8;
}

message LastSceneData {
	oneof lastscenedata_oneof {
		uint32 SceneId = 1;
		Position Pos = 2;
		int32 SceneAreaId = 3;
	}
}

message SceneLuaData {
	message SceneLuaInfoDict {
		uint32 k = 1;
		string value = 2;
	}

	repeated SceneLuaInfoDict SceneLuaInfo = 1;
}

message PioneerData {
	message PioneerDataDict {
		uint32 k = 1;
		PioneerInfo value = 2;
	}

	repeated PioneerDataDict InfoMap = 1;
}

message PioneerInfo {
	oneof pioneerinfo_oneof {
		uint32 CurrentTotal = 1;
		uint32 Id = 5;
		EErrorCode ErrCode = 6;
	}

	message TargetsDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message AwardsDict {
		int32 k = 1;
		bool value = 2;
	}

	message EnteredZonesDict {
		uint32 k = 1;
		bool value = 2;
	}

	repeated TargetsDict Targets = 2;
	repeated AwardsDict Awards = 3;
	repeated EnteredZonesDict EnteredZones = 4;
}

	
message ItemPackage {
	oneof itempackage_oneof {
		int32 QuickBar = 3;
		int32 ItemUuid = 4;
	}

	message PackagesDict {
		int32 k = 1;
		Package value = 2;
	}

	message UnlockItemsDict {
		int32 k = 1;
		int32 value = 2;
	}

	message UseGroupCdDict {
		int32 k = 1;
		int64 value = 2;
	}

	repeated PackagesDict Packages = 1;
	repeated UnlockItemsDict UnlockItems = 2;
	repeated UseGroupCdDict UseGroupCd = 5;
}

message Package {
	oneof package_oneof {
		int32 Type = 1;
		int32 MaxCapacity = 2;
		int64 PublicCd = 5;
		int32 ChangeVersion = 6;
	}

	message ItemCdDict {
		int32 k = 1;
		int64 value = 2;
	}

	message ItemsDict {
		int64 k = 1;
		Item value = 2;
	}

	repeated ItemCdDict ItemCd = 3;
	repeated ItemsDict Items = 4;
}

message Item {
	oneof item_oneof {
		int64 Uuid = 1;
		int32 ConfigId = 2;
		int64 Count = 3;
		int32 Invalid = 4;
		EItemBindFlag BindFlag = 5;
		int64 CreateTime = 6;
		int64 ExpireTime = 7;
		int32 OptSrc = 8;
		int32 Quality = 9;
		EquipAttr EquipAttr = 10;
		ModAttr ModAttr = 11;
		int64 CoolDownExpireTime = 12;
		ModNewAttr ModNewAttr = 13;
		AffixData AffixData = 14;
		int32 RewardId = 16;
	}

	message ExtendAttrDict {
		int32 k = 1;
		ItemExtendData value = 2;
	}

	message GeneSequenceDict {
		int32 k = 1;
		int32 value = 2;
	}

	repeated ExtendAttrDict ExtendAttr = 15;
	repeated GeneSequenceDict GeneSequence = 17;
}

message EquipAttr {
	oneof equipattr_oneof {
		int32 PerfectionValue = 7;
		int32 RecastCount = 8;
		int32 TotalRecastCount = 9;
		int32 PerfectionLevel = 13;
		int32 MaxPerfectionValue = 15;
		EquipAttrSet EquipAttrSet = 17;
		int32 BreakThroughTime = 18;
	}

	message BaseAttrsDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message BasicAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	message AdvanceAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	message RecastAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	message RareQualityAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	repeated BaseAttrsDict BaseAttrs = 4;
	repeated BasicAttrDict BasicAttr = 10;
	repeated AdvanceAttrDict AdvanceAttr = 11;
	repeated RecastAttrDict RecastAttr = 12;
	repeated RareQualityAttrDict RareQualityAttr = 14;
}

message EquipAttrSet {
	message BasicAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	message AdvanceAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	message RecastAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	message RareQualityAttrDict {
		int32 k = 1;
		int32 value = 2;
	}

	repeated BasicAttrDict BasicAttr = 1;
	repeated AdvanceAttrDict AdvanceAttr = 2;
	repeated RecastAttrDict RecastAttr = 3;
	repeated RareQualityAttrDict RareQualityAttr = 4;
}

message ModAttr {
	oneof modattr_oneof {
		int32 LoadFlag = 1;
		int32 Type = 2;
		int32 Level = 3;
	}

	repeated ModAttrInfo ModAttrInfo = 4;
}

message ModAttrInfo {
	oneof modattrinfo_oneof {
		int32 Type = 1;
		int32 Id = 2;
		int32 Value = 3;
	}

	message EffectParameterDict {
		uint32 k = 1;
		string value = 2;
	}

	repeated EffectParameterDict EffectParameter = 4;
}

message ModNewAttr {
	repeated int32 ModParts = 1;
	repeated ModPartUpgradeRecord UpgradeRecords = 2;
}

message ModPartUpgradeRecord {
	oneof modpartupgraderecord_oneof {
		int32 PartId = 1;
		bool IsSuccess = 2;
	}
}

message ItemExtendData {
	int32 Id = 1;
	int32 Value = 2;
}

message QuestDataList {
	oneof questdatalist_oneof {
		uint32 TrackingId = 3;
		int64 WorldQuestTimeStamp = 6;
		uint64 Version = 16;
	}

	message QuestMapDict {
		uint32 k = 1;
		QuestData value = 2;
	}

	message FinishQuestDict {
		uint32 k = 1;
		bool value = 2;
	}

	message FinishResetQuestDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message HistoryMapDict {
		uint32 k = 1;
		QuestHistory value = 2;
	}

	message WorldQuestInfoDict {
		uint32 k = 1;
		WorldQuestInfo value = 2;
	}

	message AllWorldQuestListDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message BlueWorldQuestMapDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message FilterEventIdDict {
		int32 k = 1;
		worldQuestList value = 2;
	}

	message TrackOptionalQuestDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message FinishResetQuestCountDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	message AcceptQuestMapDict {
		uint32 k = 1;
		bool value = 2;
	}

	repeated QuestMapDict QuestMap = 1;
	repeated FinishQuestDict FinishQuest = 2;
	repeated FinishResetQuestDict FinishResetQuest = 4;
	repeated HistoryMapDict HistoryMap = 5;
	repeated WorldQuestInfoDict WorldQuestInfo = 7;
	repeated AllWorldQuestListDict AllWorldQuestList = 8;
	repeated BlueWorldQuestMapDict BlueWorldQuestMap = 9;
	repeated FilterEventIdDict FilterEventId = 10;
	repeated uint32 AcceptQuestList = 11;
	repeated uint32 FollowWorldQuestList = 12;
	repeated TrackOptionalQuestDict TrackOptionalQuest = 13;
	repeated FinishResetQuestCountDict FinishResetQuestCount = 14;
	repeated AcceptQuestMapDict AcceptQuestMap = 15;
}

message QuestData {
	oneof questdata_oneof {
		uint32 Id = 1;
		uint32 SetpId = 2;
		uint32 State = 3;
		int64 StepLimitTime = 6;
		int32 StepStatus = 7;
		uint32 AddLimitTime = 8;
	}

	message TargetNumDict {
		int32 k = 1;
		int32 value = 2;
	}

	message TargetMaxNumDict {
		int32 k = 1;
		int32 value = 2;
	}

	message TargetTypeDict {
		int32 k = 1;
		int32 value = 2;
	}

	repeated TargetNumDict TargetNum = 4;
	repeated TargetMaxNumDict TargetMaxNum = 5;
	repeated TargetTypeDict TargetType = 9;
}

message QuestHistory {
	message StepHistoryDict {
		uint32 k = 1;
		uint32 value = 2;
	}

	repeated StepHistoryDict StepHistory = 1;
}

message WorldQuestInfo {
	oneof worldquestinfo_oneof {
		uint32 FinishPoints = 1;
		uint32 ExceedingPoints = 3;
	}

	repeated uint32 Rewards = 2;
}

message worldQuestList {
	repeated int32 QuestList = 1;
}

message SettingData {
	message SettingMapDict {
		int32 k = 1;
		string value = 2;
	}

	repeated SettingMapDict SettingMap = 1;
}

message MiscInfo {
	message ExpressionIdsLearnedDict {
		int32 k = 1;
		int32 value = 2;
	}

	repeated ExpressionIdsLearnedDict ExpressionIdsLearned = 1;
}

message ExchangeItem {
	message ExchangeInfoDict {
		int32 k = 1;
		ExchangeInfo value = 2;
	}

	repeated ExchangeInfoDict ExchangeInfo = 1;
}

message ExchangeInfo {
	oneof exchangeinfo_oneof {
		int32 Id = 1;
	}

	message ExchangeInfoDict {
		int32 k = 1;
		ExchangeData value = 2;
	}

	repeated ExchangeInfoDict ExchangeData = 2;
}

message ExchangeData {
	oneof exchangedata_oneof {
		int32 ItemConfigId = 1;
		int32 Unlock = 2;
		int32 CurExchangeCount = 3;
		int64 ExpireTime = 4;
		int64 LastRefreshTime = 5;
	}
}

/*message EquipList {
	
}*/

message SyncNearEntities {
	repeated Entity Appear = 1;
	repeated DisappearEntity Disappear = 2;
}

message Entity {
	int64 Uuid = 1;
	EEntityType EntType = 2;
	AttrCollection Attrs = 3;
	TempAttrCollection TempAttrs = 4;
	ActorBodyPartInfos BodyPartInfos = 5;
	SeqPassiveSkillInfo PassiveSkillInfos = 6;
	BuffInfoSync BuffInfos = 7;
}

message DisappearEntity {
	int64 Uuid = 1;
	EDisappearType Type = 2;
}

message BuffInfoSync {
	oneof buffinfosync_oneof {
		int64 Uuid = 1;		
	}
	repeated BuffInfo BuffInfos = 2;
}

message BuffInfo {
	oneof buffinfo_oneof {
		int32 BuffUuid = 1;
		int32 BaseId = 2;
		int32 Level = 3;
		int64 HostUuid = 4;
		int32 TableUuid = 5;
		int64 CreateTime = 6;
		int64 FireUuid = 7;
		int32 Layer = 8;
		int32 PartId = 9;
		int32 Count = 10;
		int32 Duration = 11;
		FightSourceInfo FightSourceInfo = 12;
	}

	repeated BuffEffectLogicInfo LogicEffect = 13;
}

message FightSourceInfo {
	oneof fightsourceinfo_oneof {
		int32 FightSourceType = 1;
		int32 SourceConfigId = 2;
	}
}

message BuffEffectLogicInfo {
	oneof buffeffectlogicinfo_oneof {
		EBuffEffectLogicPbType EffectType = 1;
		bytes RawData = 2;
		bool IsLoop = 3;
	}
}

message Position {
	float X = 1;
	float Y = 2;
	float Z = 3;
	float Dir = 4;
	
}

message AffixData {
	repeated int32 AffixIds = 1;
}

message UserFightAttr {
	int64 CurHp = 1;
	int64 MaxHp = 2;
	float OriginEnergy = 3;
	repeated uint32 ResourceIds = 4;
	repeated uint32 Resources = 5;
	int32 IsDead = 6;
	int64 DeadTime = 7;
	int32 ReviveId = 8;
	repeated SkillCdInfo CdInfo = 9;
}

message SkillCdInfo {
	int32 SkillLevelId = 1;
	int64 SkillBeginTime = 2;
	int32 Duration = 3;
	uint32 SkillCDType = 4;
	int64 ProfessionHoldBeginTime = 6;
	int32 ChargeCount = 7;
	int32 ValidCDTime = 8;
	int32 SubCDRatio = 9;
	int64 SubCDFixed = 10;
	int32 AccelerateCDRatio = 11;
}

enum EBuffEffectLogicPbType {
	PlayEffect = 0;
	Gravity = 1;
	ParabolaEffect = 2;
	Linking = 3;
	ConfusionEffect = 4;
	ZoomScale = 5;
	BuffProfessionEffect = 7;
	TeleportBelt = 8;
	BuffEffectRainbow = 9;
	BuffEffectAttrHUD = 11;
	BuffEffectShop = 12;
	BuffEffectProgress = 13;
	BuffEffectEnergyDisplay = 14;
	BuffEffectStopAll = 15;
	BuffEffectLayerChange = 16;
	Tension = 17;
}

enum EGender {
	GenderNull = 0;
	GenderMale = 1;
	GenderFemale = 2;
}

enum EDamageType {
	Normal = 0;
	Miss = 1;
	Heal = 2;
	Immune = 3;
	Fall = 4;
	Absorbed = 5;
}

enum EErrorCode {
	ErrSuccess = 0;
	ErrNoRecord = 101;
	ErrExceptionCancel = 102;
	ErrDBException = 103;
	ErrDBSeqException = 104;
	ErrDBSceneException = 105;
	ErrDBTokenException = 106;
	ErrCancelled = 201;
	ErrUnknownRpc = 202;
	ErrInvalidArgument = 203;
	ErrDeadlineExceeded = 204;
	ErrNotFound = 205;
	ErrAlreadyExists = 206;
	ErrPermissionDenied = 207;
	ErrResourceExhausted = 208;
	ErrFailedPrecondition = 209;
	ErrAborted = 210;
	ErrOutOfRange = 211;
	ErrUnimplemented = 212;
	ErrInternal = 213;
	ErrUnavailable = 214;
	ErrDataLoss = 215;
	ErrUnauthenticated = 216;
	ErrSystemMax = 999;
	ErrDBError = 1000;
	ErrCreateOpenInfo = 1001;
	ErrCreateAccountInfo = 1002;
	ErrCreateCharInfo = 1003;
	ErrCreateAccountToken = 1004;
	ErrGetOpenInfo = 1005;
	ErrGetAccountInfo = 1006;
	ErrGetCharInfo = 1007;
	ErrGetAccountToken = 1008;
	ErrLoginInQueue = 1009;
	ErrOtherLogin = 1010;
	ErrServerError = 1011;
	ErrNoAccountInfo = 1012;
	ErrNoCharInfo = 1013;
	ErrTokenExpired = 1014;
	ErrUpdateTokenFail = 1015;
	ErrRegIntoSceneError = 1016;
	ErrLoginTypeErr = 1017;
	ErrChangeMapErr = 1018;
	ErrLoginPlatformErr = 1019;
	ErrVersionErr = 1020;
	ErrDelayOffLineKickOff = 1021;
	ErrServiceLanguageError = 1022;
	NoEnterScene = 1023;
	ModIDNotOpen = 1024;
	ErrFaceData = 1025;
	ErrInitProfession = 1026;
	ErrSceneCloseKickoff = 1027;
	ErrLoginReconnectKick = 1028;
	ErrLoginErrorResume = 1029;
	ErrRepeatedLogin = 1030;
	ErrRestrictLogin = 1031;
	ErrRestrictBlack = 1032;
	ErrSdkVerifyFail = 1033;
	ErrSdkTokenExpired = 1034;
	ErrServerNotOpen = 1035;
	ErrServerEndOpen = 1036;
	ErrNormalKick = 1037;
	ErrServerBusy = 1038;
	ErrServerClose = 1039;
	ErrExitGame = 1040;
	ErrHopeKick = 1041;
	ErrClientVersionError = 1042;
	ErrInvalidDeviceId = 1043;
	ErrInvalidSystemType = 1044;
	ErrDeleteChar = 1045;
	ErrCancelDeleteChar = 1046;
	ErrCancelDeleteCharIsDelete = 1047;
	ErrIntoSceneOwnerFail = 1048;
	ErrSceneQueueUp = 1050;
	ErrProtocolVersionErr = 1051;
	ErrConfigVersionErr = 1052;
	ErrStateEventFailed = 1053;
	ErrSelectCharDoing = 1054;
	ErrSelectCharDeleted = 1055;
	ErrLoginChannelMax = 1056;
	ErrDeleteAccountKick = 1057;
	ErrIsDeleteAccount = 1058;
	ErrIsVersionKick = 1059;
	ErrNotQQChnnel = 1060;
	ErrIncorrectLaunchPlatform = 1061;
	ErrConditionWrong = 1062;
	ErrNotSupportLoginType = 1063;
	ErrSceneNotExist = 2001;
	ErrUserNotExist = 2002;
	ErrComponentNotExist = 2003;
	ErrSceneConfigNotExist = 2004;
	ErrServiceNotExist = 2005;
	ErrDataContainerNotExist = 2006;
	ErrAsynchronousReturn = 2007;
	ErrConfigNotExist = 2008;
	ErrNotUser = 2009;
	ErrConfigError = 2010;
	ErrActorNotExist = 2011;
	ErrCutSceneAlreadyPlayed = 2012;
	ErrFunctionUnlock = 2020;
	ErrFunctionClosed = 2021;
	ErrUserPlayerNotFurniturePackage = 2022;
	ErrSysInnerError = 2200;
	ErrSysWebClientNull = 2201;
	ErrSysWebRequestTimeOut = 2202;
	ErrSysWebReturnError = 2203;
	ErrRequestTooFrequently = 2204;
	ErrArgStringTooLong = 2251;
	ErrArgStringEmpty = 2252;
	ErrArgArrayTooBig = 2253;
	ErrArgArrayEmpty = 2254;
	ErrArgMapTooBig = 2255;
	ErrArgMapEmpty = 2256;
	ErrItemNotExist = 2300;
	ErrPackageNotExist = 2301;
	ErrPackageFull = 2302;
	ErrItemExpireTime = 2303;
	ErrItemPackageGridNotEnough = 2304;
	ErrItemUUIDError = 2305;
	ErrItemNotEnough = 2306;
	ErrOptTypeError = 2307;
	ErrItemInCoolDown = 2308;
	ErrItemNotUse = 2309;
	ErrItemEffectTypeError = 2310;
	ErrItemParamError = 2311;
	ErrItemAddBuffError = 2312;
	ErrItemAdd = 2313;
	ErrUseItemState = 2314;
	ErrBatchUse = 2315;
	ErrFullSendMail = 2316;
	ErrItemNumZero = 2317;
	ErrItemSelectAwardIllegalNum = 2318;
	ErrItemSelectAwardIllegalPos = 2319;
	ErrItemSelectLimit = 2320;
	ErrItemPeriodGainExceeded = 2321;
	ErrItemNoRecycle = 2322;
	ErrItemRecycleBeyondMaxGrid = 2323;
	ErrItemRecycleBeyondMaxNum = 2324;
	ErrItemRecycleIdNoMatchItemId = 2325;
	ErrItemRecycleIllegalId = 2326;
	ErrItemLimitCount = 2327;
	ErrItemFriendPontExceeded = 2328;
	ErrItemToySingleEntUseExceeded = 2329;
	ErrItemToySceneUseExceeded = 2330;
	ErrItemToyUseInDisableArea = 2331;
	ErrItemToySingleCellUseExceeded = 2332;
	ErrMonthlyCardNotExists = 2380;
	ErrMonthlyCardDataError = 2381;
	ErrMonthlyCardDayAwardReceived = 2382;
	ErrMonthlyCardLimitCount = 2383;
	ErrCommunityNoHome = 2400;
	ErrNotHouseOwner = 2401;
	ErrHomeLandExisted = 2402;
	ErrHomeLandContentWrongful = 2403;
	ErrHouseLivetogetherCD = 2404;
	ErrHomeLandNotExisted = 2405;
	ErrHomeLandNotInScene = 2406;
	ErrHomeLandIsInvitation = 2407;
	ErrHomeLandInsufficientAuthority = 2408;
	ErrHomeLandTransferRequestPending = 2409;
	ErrHomeLandTransferRequestTimeout = 2410;
	ErrHomeLandTransferCD = 2411;
	ErrHomelandTargetIsHasHome = 2412;
	ErrHomelandTargetIsOwner = 2413;
	ErrHomelandNotOwnerCannotOperate = 2414;
	ErrHomeLandHasHouse = 2415;
	ErrHomeLandContentTooLong = 2416;
	ErrHomeLandClutterNotExist = 2417;
	ErrHouseNameOrStatementCD = 2418;
	ErrHouseIntroductionStatementCD = 2419;
	ErrCommunityBuildInvalidRecipeId = 2420;
	ErrCommunityBuildRecipeIsUnlock = 2421;
	ErrCommunityBuildMax = 2422;
	ErrCommunityBuildNoAuthority = 2423;
	ErrCommunityNotBuildCannotCancel = 2424;
	ErrCommunityBuildNotSelfCannotCancel = 2425;
	ErrCommunityNotBuildCannotAccelerate = 2426;
	ErrCommunityBuildNotSelfCannotAccelerate = 2427;
	ErrCommunityBuildCannotAccelerate = 2428;
	ErrCommunityBuildAlreadyAccelerate = 2429;
	ErrCommunityBuildInDungeon = 2430;
	ErrCommunityBuildRecipeIsLock = 2431;
	ErrCommunityBuildRecipeNotItemUnlock = 2432;
	ErrCommunityBuildInvalidCount = 2433;
	ErrCommunityNotBuildCannotReceive = 2434;
	ErrCommunityCanNotBuild = 2435;
	ErrHomeLandCohabitantLimit = 2436;
	ErrHomeLandRootNotQuitCohabitant = 2437;
	ErrHomeLandNotOwnerCannotQuitCohabitant = 2438;
	ErrHomeLandCohabitantIsExiting = 2439;
	ErrHomeLandCohabitantNotExists = 2440;
	ErrHomeLandCohabitantExitRequestExists = 2441;
	ErrHomeLandCohabitantDismiss = 2442;
	ErrHomeLandNotInvitation = 2443;
	ErrHomeLandCohabitantInvitationTimeout = 2444;
	ErrHomeLandCohabitantNotFriend = 2445;
	ErrHomeLandCohabitantFriendLevel = 2446;
	ErrHomeLandCohabitantLevel = 2447;
	ErrHomeLandInviteCohabitantNotOwner = 2448;
	ErrCommunityWarehouseGridFull = 2451;
	ErrCommunityWarehouseNoAuthority = 2452;
	ErrCommunityWarehouseGridPosItemNoEnough = 2453;
	ErrHomeLandInsufficientFurniture = 2454;
	ErrCommunityWarehouseTakeOutCountLimit = 2455;
	ErrHomeLandTaskNotExist = 2456;
	ErrHomeLandTaskTimeNotEnough = 2457;
	ErrHomeLandTaskAlreadyFinished = 2458;
	ErrHomeLandTaskItemNotEnough = 2459;
	ErrHomeLandCurLevelError = 2461;
	ErrHomeLandExpNotEnough = 2462;
	ErrHomeLandAlreadyMaxLevel = 2463;
	ErrHomeLandLevelLocked = 2464;
	ErrHomeLandLevelConfigError = 2465;
	ErrCommunityEditorNotEditable = 2466;
	ErrCommunityEditorNotFurniture = 2467;
	ErrCommunityEditorNotOutdoor = 2468;
	ErrCommunityEditorNotIndoor = 2469;
	ErrCommunityEditorOverMax = 2470;
	ErrCommunityEditorOverTypeMax = 2471;
	ErrCommunityEditorFurnitureNotEnough = 2472;
	ErrCommunityEditorFurnitureNotExist = 2473;
	ErrCommunityEditorOverMaxGroup = 2474;
	ErrCommunityEditorNoStructure = 2475;
	ErrCommunityEditorGroupMaxStructure = 2476;
	ErrCommunityEditorStructureInGroup = 2477;
	ErrCommunityEditorGroupNotExist = 2478;
	ErrCommunityEditorAlreadyExist = 2479;
	ErrHomeLandSellItemNotExist = 2481;
	ErrHomeLandLeftNumNotEnough = 2482;
	ErrHomeLandSellShopLocked = 2483;
	ErrHomeLandSeedExist = 2486;
	ErrHomeLandItemNotOwner = 2487;
	ErrHomeLandSeedStateError = 2488;
	ErrHomeLandNoSeed = 2489;
	ErrHomeLandNoWater = 2490;
	ErrHomeLandFertilizerMaxNumLimit = 2491;
	ErrHomeLandNotFertilize = 2492;
	ErrHomeLandNotPollen = 2493;
	ErrHomeLandAlreadyPollen = 2494;
	ErrHomeLandNotHarvest = 2495;
	ErrHomeLandPickUpSinglePlayerLimit = 2496;
	ErrHomeLandPickUpTotalLimit = 2497;
	ErrHomeLandPickUpFlowerNotFinished = 2498;
	ErrHomeLandPickUpOwner = 2499;
	ErrHomeLandGainNotOwner = 2500;
	ErrHomeLandItemFullGrid = 2501;
	ErrHomeLandFurnitureFull = 2502;
	ErrComposeItemNotEnough = 2571;
	ErrComposeFailed = 2572;
	ErrRedemptionItemNotExist = 2573;
	ErrRedemptionItemMaxCount = 2574;
	ErrRedemptionItemNotEnough = 2575;
	ErrRedemptionItemGender = 2576;
	ErrAwardConfigNotFound = 2600;
	ErrAwardConfigWeightError = 2601;
	ErrAwardConfigLimitAndContentNotMatch = 2602;
	ErrAwardConfigContentSizeError = 2603;
	ErrAwardConfigContentRatesSizeError = 2604;
	ErrAwardConfigContentWeightSizeError = 2605;
	ErrAwardConfigGroupContentEmpty = 2606;
	ErrAwardConfigGroupNumEmpty = 2607;
	ErrAwardConfigGroupContentNoMatchGroupNum = 2608;
	ErrAwardConfigNoRandomDrop = 2609;
	ErrAwardConfigNoSelectAward = 2610;
	ErrAwardConfigSelfSelectContentNoItem = 2611;
	ErrAwardConfigWeightRateMustOne = 2612;
	ErrAwardConfigGroupContentRandomNoMatch = 2613;
	ErrAwardConfigGroupContentError = 2614;
	ErrAwardConfigPackageContentRandomNoMatch = 2615;
	ErrAwardConfigLevelUpPackConfigPackageNoMatch = 2616;
	ErrAwardConfigProItemRuleNoMatch = 2617;
	ErrAwardConfigPackageContentEmpty = 2618;
	ErrAwardConfigDropContentSize = 2619;
	ErrAwardConfigDropContentNum = 2620;
	ErrAwardConfigGroupRateEmpty = 2621;
	ErrAwardConfigGroupWeightEmpty = 2622;
	ErrAwardInnerError = 2623;
	ErrAwardIllegalRandomType = 2624;
	ErrAwardConditionNoMeet = 2625;
	ErrAwardRandomTypeNone = 2626;
	ErrAwardRandomTypeNoMatch = 2627;
	ErrAwardActorIsNull = 2628;
	ErrEquipWashAttrNotExist = 2700;
	ErrNotEquipInCombat = 2701;
	ErrEquipPart = 2702;
	ErrComposeItemNotExist = 2750;
	ErrPickupDropItemDistance = 2800;
	ErrPickupDropItemPackageFull = 2801;
	ErrPickupDropItemNoAuthority = 2802;
	ErrLayerActorExist = 2851;
	ErrTeamCreateHas = 2900;
	ErrTeamIllTarget = 2901;
	ErrTeamCreateTryLater = 2902;
	ErrTeamGetNo = 2903;
	ErrTeamListEmpty = 2904;
	ErrTeamInner = 2905;
	ErrTeamNoLeader = 2906;
	ErrTeamInMatch = 2907;
	ErrTeamCustomizeTarget = 2908;
	ErrTeamNoOwn = 2909;
	ErrTeamTickSelf = 2910;
	ErrTeamNoMem = 2911;
	ErrTeamApplyingLeader = 2912;
	ErrTeamHasBeLeader = 2913;
	ErrTeamNoTransferSelf = 2914;
	ErrTeamNoLeaderTransfer = 2915;
	ErrTeamHasOwnTeam = 2916;
	ErrTeamNoExist = 2917;
	ErrTeamApplyInCD = 2918;
	ErrTeamApplyExpire = 2919;
	ErrTeamJoinOther = 2920;
	ErrTeamMemMax = 2921;
	ErrTeamNoInvited = 2924;
	ErrTeamIsMatching = 2925;
	ErrTeamIllegalTag = 2926;
	ErrTeamNoMatching = 2927;
	ErrTeamIllegalActivity = 2928;
	ErrTeamInActivity = 2929;
	ErrTeamNoMeetCondition = 2930;
	ErrTeamWaitVoting = 2931;
	ErrTeamDoingActivity = 2932;
	ErrTeamNoInVoting = 2933;
	ErrTeamVoteEnd = 2934;
	ErrTeamHasVoted = 2935;
	ErrTeamInviteCD = 2936;
	ErrTeamApplyLeadCD = 2937;
	ErrTeamMoreMaxWorlds = 2938;
	ErrTeamValidApplyInfo = 2939;
	ErrTeamInMatchCancelCD = 2940;
	ErrTeamMatchFinished = 2941;
	ErrTeamMatchWaitSec = 2942;
	ErrTeamMemWorldFull = 2943;
	ErrTeamMemNotLeader = 2944;
	ErrTeamLeaderNotStaticScene = 2945;
	ErrTeamLeaderCallDoing = 2946;
	ErrTeamIllegalCallOperator = 2947;
	ErrTeamLeaderIllegalCallOperator = 2948;
	ErrTeamNoMemCall = 2949;
	ErrTeamLeaderCallEnd = 2950;
	ErrTeamSameScene = 2951;
	ErrTeamNotSameScene = 2952;
	ErrTeamMemTooMore = 2953;
	ErrTeamMemInDungeon = 2954;
	ErrTeamMemTooLess = 2955;
	ErrTeamIllegalInviteType = 2956;
	ErrTeamMemberNotInScene = 2957;
	ErrTeamLeaderReadyCheckTimeNotReady = 2958;
	ErrTeamExistDungeonCheck = 2959;
	ErrTeamTargetMatchTalentLimit = 2960;
	ErrTeamEditGroupNotAllowed = 2961;
	ErrTeamGroupNotExist = 2962;
	ErrTeamTargetNoMatchMemberType = 2963;
	ErrDecomposeItemNotExist = 3000;
	ErrDecomposeItemNotEnough = 3001;
	ErrRefineEnergyNotEnough = 3002;
	ErrRefineItemMaxCount = 3003;
	ErrRefineItemNotExist = 3004;
	ErrRefineItemColumnNotUnlock = 3005;
	ErrRefineItemColumnUnlock = 3006;
	ErrRefineItemExist = 3007;
	ErrEnergyLimitMax = 3008;
	ErrRefineItemColumnNotEmpty = 3009;
	ErrProfessionNotExist = 3056;
	ErrModSlotNotUnlock = 3058;
	ErrChangeProfessionStateFail = 3065;
	ErrChangeProfessionCDFail = 3066;
	ErrProfessionSkinNotActive = 3071;
	ErrProfessionSkinActive = 3072;
	ErrProfessionNotUseSkin = 3073;
	ErrProfessionSkillSkinActive = 3074;
	ErrProfessionSkillSkinNotActive = 3075;
	ErrProfessionSkillNotActive = 3076;
	ErrCharOffline = 3101;
	ErrUserDataBaseError = 3102;
	ErrCharGetFail = 3103;
	ErrAlreadyAlive = 3200;
	ErrReviveParam = 3201;
	ErrStateIllegal = 3202;
	ErrStateNoChange = 3203;
	ErrReviveConsumeNotEnough = 3204;
	ErrReviveByOtherForbid = 3205;
	ErrReviveTimeNotArrived = 3206;
	ErrReviveBossBattle = 3207;
	ErrReviveCountLimit = 3208;
	ErrReviveInDeadTp = 3209;
	ErrDungeonPlayTypeError = 3301;
	ErrDungeonNotExist = 3302;
	ErrDungeonCreateError = 3303;
	ErrCantChangeDungeon = 3304;
	ErrDungeonLock = 3305;
	ErrPioneerFail = 3306;
	ErrAwardFail = 3307;
	ErrGsNotEnough = 3308;
	ErrQuestNotCompleted = 3309;
	ErrDungeonNotClear = 3310;
	ErrConditionNotExist = 3311;
	ErrAwardReceived = 3312;
	ErrCantRepeatedPlay = 3313;
	ErrNeedPassPreRoom = 3314;
	ErrDungeonEnterCountLimit = 3315;
	ErrDungeonScoreError = 3316;
	ErrDungeonRepeatedVote = 3317;
	ErrDungeonChallengeAwardState = 3318;
	ErrDungeonChallengeAffixNotFound = 3319;
	ErrDungeonStateNotActive = 3320;
	ErrDungeonCantVoteSelf = 3321;
	ErrDungeonPlayerNotEnough = 3322;
	ErrDungeonPlayerFull = 3323;
	ErrDungeonCantHeroKey = 3324;
	ErrDungeonNotSettlement = 3325;
	ErrDungeonNotFindRollItem = 3326;
	ErrDungeonCantRoll = 3327;
	ErrDungeonRollFinish = 3328;
	ErrDungeonSelectError = 3329;
	ErrDungeonAiModeError = 3330;
	ErrDungeonTargetNotFinish = 3331;
	ErrDungeonTargetBeAward = 3332;
	ErrDungeonSinglePlayerMore = 3333;
	ErrDungeonAiGroupNotEnough = 3334;
	ErrDungeonNoPass = 3335;
	ErrDungeonCloseSceneId = 3336;
	ErrDungeonEnterTypeError = 3337;
	ErrDungeonActorCount = 3338;
	ErrDungeonDiffLocked = 3339;
	ErrDungeonPreBattleVoteCd = 3340;
	ErrDungeonBossInvalid = 3341;
	ErrDungeonNoUser = 3342;
	ErrDungeonUserInvalid = 3343;
	ErrDungeonAwardualification = 3344;
	ErrDungeonAwardTriesLimit = 3345;
	ErrFashionIsLimit = 3401;
	ErrFashionNotFound = 3402;
	ErrFashionSlotEmpty = 3403;
	ErrFashionIDNotFound = 3404;
	ErrFashionLock = 3405;
	ErrFashCollectionAwardAlread = 3406;
	ErrFashCollectionScoreNotEnough = 3407;
	ErrFashCollectionAwardAlreadMonth = 3408;
	ErrFashionAlreadUnlock = 3409;
	ErrFashionAdvanceNotExist = 3410;
	ErrFashionBaseNotUnlock = 3411;
	ErrFashionAdvanceAlreadyUnlock = 3412;
	ErrCameraNoExistAlbum = 3501;
	ErrCameraBeyondPhotoNum = 3502;
	ErrCameraBeyondAlumNum = 3503;
	ErrCameraNoAccessRight = 3504;
	ErrCameraNoExistPhoto = 3505;
	ErrCameraBeyondWordNum = 3506;
	ErrCameraPhotoNoInAlbum = 3507;
	ErrCameraInnerError = 3508;
	ErrCameraIllegalRight = 3509;
	ErrCameraNoExistChar = 3510;
	ErrCameraNoDelCloudAlbum = 3511;
	ErrCameraBeyondMaxURlLen = 3512;
	ErrCameraBeyondMaxXMLLen = 3513;
	ErrCameraBeyondMaxNameLen = 3514;
	ErrCameraIllegalUrl = 3515;
	ErrCameraRenderInfoEmpty = 3516;
	ErrCameraBeyondPhotoMaxSize = 3517;
	ErrCameraIllegalPictureType = 3518;
	ErrCameraTypeRepeated = 3519;
	ErrCameraWithoutOriginal = 3520;
	ErrCameraWithoutThumbnailOrRender = 3521;
	ErrCameraPhotoNameEmpty = 3522;
	ErrCameraPhotoNameOutMaxLen = 3523;
	ErrCameraAlbumNameEmpty = 3524;
	ErrCameraPhotoHasDel = 3525;
	ErrCameraSysInnerError = 3526;
	ErrCameraIllegalPictureId = 3527;
	ErrCameraBeyondMaxExtraLen = 3528;
	ErrCameraNoIncludeOriginal = 3529;
	ErrCameraNoDealingPhoto = 3530;
	ErrCameraNoDealingPhotoType = 3531;
	ErrCameraNoAnyAlbum = 3532;
	ErrCameraNoPassReview = 3533;
	ErrCameraPhotoMissImage = 3534;
	ErrCameraWithoutThumbnail = 3535;
	ErrCameraBeyondMaxUploadTimes = 3536;
	ErrInvalidLifeProfessionId = 3601;
	ErrLifeProfessionIsUnlock = 3602;
	ErrLifeProfessionMaxLevel = 3603;
	ErrLifeProfessionLevelNotEnough = 3604;
	ErrLifeProfessionLevelRewardGot = 3605;
	ErrInvalidLifeProfessionSpecializationId = 3606;
	ErrLifeProfessionSpecializationNotEnough = 3607;
	ErrLifeProfessionSpecializationUpgradeError = 3608;
	ErrLifeProfessionPointNotEnough = 3609;
	ErrInvalidLifeProfessionTargetId = 3610;
	ErrLifeProfessionTargetNotEnough = 3611;
	ErrLifeProfessionRewardCanNotGet = 3612;
	ErrLifeProfessionEnergyChange = 3613;
	ErrLifeProfessionRecipeIsUnlock = 3614;
	ErrLifeProfessionRecipeNotExist = 3615;
	ErrLifeProfessionRecipeNotUnlock = 3616;
	ErrLifeProfessionMaxRDRecipeCount = 3617;
	ErrLifeProfessionWorkingNotEnd = 3618;
	ErrLifeProfessionAlreadyWorking = 3619;
	ErrLifeProfessionNotWorking = 3620;
	ErrLifeProfessionWorkingIsEnd = 3621;
	ErrLifeProfessionUnActiveSpecialization = 3622;
	ErrCurLevelConfigNotExist = 4001;
	ErrNeedBreakthrough = 4002;
	ErrExperienceConfigNotExist = 4003;
	ErrExperienceMismatch = 4004;
	ErrNotNeedToBreakthrough = 4005;
	ErrConsumeConfigError = 4006;
	ErrSkillNotExist = 4007;
	ErrSkillLevelMax = 4008;
	ErrSkillLevelNotExist = 4009;
	ErrSkillConfigError = 4010;
	ErrStarNotExist = 4011;
	ErrMaxStar = 4012;
	ErrMaxLevel = 4013;
	ErrSkillLevelNotEnough = 4014;
	ErrCanNotChangeActionState = 4051;
	ErrActionNotExist = 4052;
	ErrIsInteracting = 4053;
	ErrState = 4054;
	ErrRequestExpired = 4055;
	ErrStateSetFailed = 4071;
	ErrCollectIdError = 4072;
	ErrCollectStateFailed = 4073;
	ErrCollectActorErr = 4074;
	ErrCollectOutRange = 4075;
	ErrCollectConditionEquip = 4076;
	ErrCollectConditionQuest = 4077;
	ErrAlreadyCollected = 4078;
	ErrMailGetFailed = 4101;
	ErrMailIllegality = 4102;
	ErrMailIsGet = 4103;
	ErrMailIsDel = 4104;
	ErrMailAcceptorEmpty = 4105;
	ErrMailTokenInvalid = 4106;
	ErrUnRegisterType = 4201;
	ErrIndexNotFound = 4202;
	ErrCantOpenTreasureBox = 4203;
	ErrPersonalStateEnd = 4204;
	ErrPersonalObjectStatus = 4205;
	ErrExp = 4301;
	ErrLevel = 4302;
	ErrAward = 4303;
	ErrReceivedLevelAward = 4304;
	ErrLevelNotEnough = 4305;
	ErrRoleLevelNoRewards = 4306;
	ErrUnionNotHaveLimit = 4401;
	ErrUnionIsNotMember = 4402;
	ErrUnionOfficialNotExits = 4403;
	ErrUnionOfficialTooMany = 4404;
	ErrUnionHas = 4405;
	ErrUnionReqCd = 4406;
	ErrUnionReqHas = 4407;
	ErrUnionFull = 4408;
	ErrUnionFailed = 4409;
	ErrUnionNameWrongful = 4410;
	ErrUnionNameUsed = 4411;
	ErrUnionNameOccupied = 4412;
	ErrApplyMax = 4415;
	ErrUnionChangeNameCD = 4416;
	ErrUnionNameSizeError = 4417;
	ErrDeclarationSize = 4418;
	ErrDeclarationError = 4419;
	ErrOfficialNameRepeat = 4420;
	ErrDeclarationCd = 4421;
	ErrUnionInfoCd = 4422;
	ErrUnionNotExist = 4423;
	ErrUnionIllegalConditionType = 4424;
	ErrUnionRecruitSloganTooLong = 4425;
	ErrUnionRecruitDescriptionTooLong = 4426;
	ErrUnionCreateTooOften = 4427;
	ErrUnionTagNoExist = 4428;
	ErrUnionIconTooMuch = 4429;
	ErrUnionGetListCd = 4430;
	ErrUnionBatchSearchUnionIdsTooMuch = 4431;
	ErrUnionBatchSearchCd = 4432;
	ErrUnionGetCollectedIdsCd = 4433;
	ErrUnionBeyondMaxCollectedNum = 4434;
	ErrUnionIdHasCollected = 4435;
	ErrUnionIdNoCollected = 4436;
	ErrUnionActiveValueNotEnough = 4437;
	ErrUnionIllegalActiveId = 4438;
	ErrUnionTooShortForAwards = 4439;
	ErrUnionHasActiveAwards = 4440;
	ErrUnionNoJoin = 4441;
	ErrUnionOnlyEnterSelf = 4442;
	ErrUnionNoUnlockScene = 4443;
	ErrUnionBuildingMaxLevel = 4444;
	ErrUnionBuildingUpgrading = 4445;
	ErrUnionBuildingUpgradeNoFinish = 4446;
	ErrUnionPrefixBuildNoMeet = 4447;
	ErrUnionExperienceNoEnough = 4448;
	ErrUnionMoneyNoEnough = 4449;
	ErrUnionBuildingNoUpgrading = 4450;
	ErrUnionSpeedUpItemNoEnough = 4451;
	ErrUnionSpeedUpTimesOut = 4452;
	ErrUnionTryLater = 4453;
	ErrUnionSpeedUpLevelError = 4454;
	ErrUnionUpgradeHasCompleted = 4455;
	ErrUnionIllegalBuildIdLv = 4456;
	ErrUnionBeyMaxCount = 4457;
	ErrUnionUserNoApply = 4458;
	ErrUnionNoOneKeyNoMuch = 4459;
	ErrUnionActivityNotStart = 4460;
	ErrUnionActivityNotProgress = 4461;
	ErrUnionActivityAwardGet = 4462;
	ErrUnionActivityNotEnjoy = 4463;
	ErrUnionCreateTimeTooShort = 4464;
	ErrUnionFunctionLock = 4465;
	ErrUnionEScreenLock = 4466;
	ErrUnionEScreenPositionLock = 4467;
	ErrUnionEScreenNoSet = 4468;
	ErrUnionEScreenPositionNoSet = 4469;
	ErrUnionEffectGridLock = 4470;
	ErrUnionEffectIdLock = 4471;
	ErrUnionEffectPosNoSet = 4472;
	ErrUnionEffectPosHasEnd = 4473;
	ErrUnionCrowFuncHasEnd = 4474;
	ErrUnionCrowFuncPosHasUsed = 4475;
	ErrUnionCrowFuncHasJoined = 4476;
	ErrUnionCrowFuncNoBegin = 4477;
	ErrUnionNoFinishBaseBuilding = 4478;
	ErrUnionCrowFuncIllegalFuncPos = 4479;
	ErrUnionEScreenBeyondMaxTimes = 4480;
	ErrUnionTargetFunctionLock = 4481;
	ErrUnionNoMeet = 4482;
	ErrUnionActivityAwardCd = 4483;
	ErrUnionManagerNoKicked = 4484;
	ErrUnionDanceNoBegin = 4485;
	ErrUnionDanceEnd = 4486;
	ErrUnionDanceDrawnBox = 4487;
	ErrUnionDanceBoxDrawn = 4488;
	ErrUnionDanceNoDanceId = 4489;
	ErrUnionNoJoinDance = 4490;
	ErrUnionDanceNoDancing = 4491;
	ErrUnionRejectInvite = 4492;
	ErrUnionActivityHuntEnd = 4493;
	ErrUnionApplyListFull = 4494;
	ErrUionApplyListExist = 4495;
	ErrUnionGroupIvalid = 4496;
	ErrRepeatedRequest = 4501;
	ErrHasBeenBlackened = 4502;
	ErrNotFoundCharInfo = 4503;
	ErrInner = 4504;
	ErrParam = 4505;
	ErrSetShowPicture = 4506;
	ErrSetSignature = 4507;
	ErrSetHobbyMark = 4508;
	ErrSetTimeMark = 4509;
	ErrSetRemind = 4510;
	ErrSetTop = 4511;
	ErrAddFriend = 4512;
	ErrSetProcessed = 4513;
	ErrSetRemark = 4514;
	ErrDeleteFriend = 4515;
	ErrNotFoundGroup = 4516;
	ErrNotExistInGroup = 4517;
	ErrChangeGroup = 4518;
	ErrPersonalState = 4519;
	ErrOtherFriendMax = 4520;
	ErrCurFriendMax = 4521;
	ErrConfig = 4522;
	ErrAlreadyFriend = 4523;
	ErrSearchSelf = 4524;
	ErrSuggestionCd = 4525;
	ErrGroupMax = 4526;
	ErrGroupNotExist = 4527;
	ErrGroupNameEmpty = 4528;
	ErrIllegalCharacter = 4529;
	ErrStringMax = 4530;
	ErrOtherApplicationMax = 4531;
	ErrFriendlinessAwardHasRecord = 4532;
	ErrFriendlinessLevelLowAwardLevel = 4533;
	ErrFriendBeyondAllFriendNum = 4534;
	ErrFriendIsNoUserFriend = 4535;
	ErrFriendlinessIllegalAwardLevel = 4536;
	ErrFriendlinessLevelAwardIsEmpty = 4537;
	ErrFriendBeBlackenedByTarget = 4538;
	ErrFriendApplyEachOther = 4539;
	ErrFriendCallBySmallerCharId = 4540;
	ErrFriendCallByBiggerCharId = 4541;
	ErrFriendBeBlackenedBySmaller = 4542;
	ErrFriendBeBlackenedByBigger = 4543;
	ErrFriendNoApply = 4544;
	ErrFriendApplySelf = 4545;
	ErrUserNameFormat = 4546;
	ErrFriendGetBaseTooOften = 4547;
	ErrFriendOnlyGetSelfBaseInfo = 4548;
	ErrActorGetFailed = 4601;
	ErrPivotIsActive = 4602;
	ErrPivotIsNotActive = 4603;
	ErrBreakPointIsGet = 4604;
	ErrActorIsNotPivot = 4605;
	ErrActorIsNotBreakPoint = 4606;
	ErrActorIsBreakPointNotFull = 4607;
	ErrPivotRewardIsGiven = 4608;
	ErrNotInsight = 4609;
	ErrLearnSkillFail = 4651;
	ErrRemoveSkillFail = 4652;
	ErrUpdateSkillFail = 4653;
	ErrSkillOperatorType = 4654;
	ErrContainerOperator = 4655;
	ErrExchangeFail = 4656;
	ErrExchangeFailInCombat = 4657;
	ErrAvatarBeyondMaxPictureSize = 4671;
	ErrGetTokenFailed = 4672;
	ErrPictureVerifyFailed = 4673;
	ErrPictureIllegalType = 4674;
	ErrPictureErrorInfo = 4675;
	ErrPictureSizeInconsistent = 4676;
	ErrPictureFuncTypeIllegal = 4677;
	ErrPictureCallBackJudgeIllegal = 4678;
	ErrPictureVerifyNoPass = 4679;
	ErrPictureVerifyBackParamIllegal = 4680;
	ErrPictureCallBackParamIllegal = 4681;
	ErrPictureIllegalId = 4682;
	ErrPictureCosErrors = 4683;
	ErrPictureInnerSysErr = 4684;
	ErrPictureNoSetEnvCosSecretId = 4685;
	ErrPictureNoSetEnvCosSecretKey = 4686;
	ErrPictureCheckInMachineLocked = 4687;
	ErrPictureNoTryOutItem = 4688;
	ErrPictureNoUploadItem = 4689;
	ErrPictureNoUnion = 4690;
	ErrNameSizeError = 4701;
	ErrSensitiveContent = 4702;
	ErrChangeNameFail = 4703;
	ErrChangeNameCardNotEnough = 4704;
	ErrChangeSameName = 4705;
	ErrCheckMuteWordsFailed = 4706;
	ErrCheckMuteWordsEmpty = 4708;
	ErrChangeShowIdFail = 4711;
	ErrChangeShowIdDuplicated = 4712;
	ErrChangeShowIdCardNotEnough = 4713;
	ErrFaceItemLock = 4721;
	ErrFaceItemGender = 4722;
	ErrFaceNoUploading = 4723;
	ErrFaceNoSupportFileSuffix = 4724;
	ErrFaceFileSuffixEmpty = 4725;
	ErrFaceIllegalCosKey = 4726;
	ErrFaceParseSuffixFailed = 4727;
	ErrFaceParseShortGuidFailed = 4728;
	ErrProficiencyNeedUnlock = 4751;
	ErrProficiencyUnlock = 4752;
	ErrUnlockItemNotEnough = 4753;
	ErrTaskNotFinish = 4771;
	ErrStickerAwardIsGet = 4772;
	ErrBookAwardIsGet = 4773;
	ErrInCd = 4791;
	ErrMoneyNotEnough = 4801;
	ErrShopItemCantBuy = 4802;
	ErrShopBuyBusy = 4803;
	ErrPaymentConfigNotFound = 4804;
	ErrRefreshShopCountExceed = 4806;
	ErrShopCouponNotEnough = 4807;
	ErrShopCouponLimitNum = 4808;
	ErrShopCantBuyNoPrice = 4809;
	ErrNotFoundMonster = 4901;
	ErrNotMonster = 4902;
	ErrMonsterUnlockExist = 4903;
	ErrMonsterAwardIsGet = 4904;
	ErrMonsterTargetNotFinish = 4905;
	ErrDropTypeNotSupport = 4906;
	ErrCounterNotEnough = 4907;
	ErrDropItemAlreadyPicked = 4908;
	ErrInteractionDoing = 4941;
	ErrInteractionCondition = 4942;
	ErrInteractionNotMore = 4943;
	ErrInteractionExistPos = 4944;
	ErrInteractionNotExist = 4945;
	ErrInteractionEntityNotExist = 4946;
	ErrInteractionHandleNotExist = 4947;
	ErrInteractionType = 4948;
	ErrInteractionBan = 4949;
	ErrInteractionConfig = 4950;
	ErrInteractionNotOneself = 4951;
	ErrInteractionDistance = 4952;
	ErrShowPieceIllegalPieceType = 4961;
	ErrShowPieceIllegalPieceId = 4962;
	ErrShowPieceNoInOftenUseList = 4963;
	ErrShowPieceNoUnlockList = 4964;
	ErrShowPieceRoulettePositionNoSet = 4965;
	ErrShowPieceBeyondOftenUseMaxLen = 4966;
	ErrShowPieceBeyondOftenRoulettePositionNum = 4967;
	ErrShowPieceNoCommonPiece = 4968;
	ErrShowPieceNoTakeOn = 4969;
	ErrProfessionActivated = 5001;
	ErrProfessionNotHas = 5002;
	ErrProfessionSlotErr = 5003;
	ErrProfessionRemoveErr = 5004;
	ErrProfessionChangePlanFail = 5005;
	ErrProfessionStarConfigNotExist = 5006;
	ErrProfessionStarNodeUnlock = 5007;
	ErrProfessionStarNodeNotUnlock = 5008;
	ErrProfessionReplaceSkillNotExist = 5009;
	ErrProfessionUpgradeNotGreaterCurLevel = 5010;
	ErrProfessionProfessionBeForged = 5011;
	ErrProfessionSlotTwoNotUnlock = 5012;
	ErrProfessionSkillAlreadyActive = 5013;
	ErrProfessionSkillRemodelLevelWrong = 5014;
	ErrAoyiSkillAlreadyActive = 5015;
	ErrAoyiSkillRemodelConfigNotExist = 5016;
	ErrAoyiSkillRemodelLevelWrong = 5017;
	ErrProfessionEquipInCombat = 5018;
	ErrProfessionSwitchInCombat = 5019;
	ErrProfessionDungeonNotAllowSwitch = 5020;
	ErrTalentIllegalTalentPoolId = 5101;
	ErrTalentBeyondCurTalentMaxPlanNum = 5102;
	ErrTalentPoolNoActive = 5108;
	ErrTalentPlanNoActive = 5109;
	ErrTalentIllegalTalentId = 5110;
	ErrTalentTalentHasUnlocked = 5111;
	ErrTalentTalentNoUnlocked = 5112;
	ErrTalentChangeLvPassiveTalentMoreThanInPool = 5113;
	ErrTalentRepeatedTalentId = 5114;
	ErrTalentNoPoolPassiveTalent = 5115;
	ErrTalentTalentPointsNoEnough = 5116;
	ErrTalentPassiveTalentListNoEmpty = 5118;
	ErrTalentIllegalTalentLevel = 5119;
	ErrTalentNoMeetUpgradeCondition = 5120;
	ErrTalentNoSupportDownLevelNow = 5121;
	ErrTalentNoMeetPrevTalentLv = 5122;
	ErrTalentNoMeetPrevTalentPoint = 5123;
	ErrTalentTreeNodeBDExclusive = 5124;
	ErrTalentTotalTalentPointNotEnough = 5125;
	ErrTalentPreTalentNodeNotActivated = 5126;
	ErrTalentResetTalentInCombat = 5127;
	ErrCookBookNotExist = 5151;
	ErrCookFoodNotEnough = 5152;
	ErrCookTypeMore = 5153;
	ErrCookCountMore = 5154;
	ErrCookHasBook = 5155;
	ErrCookMaterialNotMatch = 5156;
	ErrChatIllegalPrivateChatTarget = 5201;
	ErrChatInTargetBlockList = 5202;
	ErrChatSendMsgBeyondMaxWords = 5203;
	ErrChatWorldChannelIdIsZero = 5204;
	ErrChatWorldChannelIdBeyondMaxId = 5205;
	ErrChatIllegalChannelType = 5206;
	ErrChatIllegalMsgType = 5207;
	ErrChatNoInGoalChannel = 5208;
	ErrChatNeedConfigIdNotZero = 5209;
	ErrChatNeedMsgTextNotEmpty = 5210;
	ErrChatSendCdNoEnd = 5211;
	ErrChatRecordListIsEmpty = 5212;
	ErrChatTargetNotInPrivateList = 5213;
	ErrChatMsgIdMoreThanMaxReadMsgId = 5214;
	ErrChatBeyondBlockListLimit = 5215;
	ErrChatWorldChannelIdBeyondMaxNum = 5216;
	ErrChatBeyondMaxRecordId = 5217;
	ErrChatNoCreatePrivateSession = 5218;
	ErrChatPrivateSessionHasExit = 5219;
	ErrChatBeBan = 5220;
	ErrChatFileIdTooLong = 5221;
	ErrChatFileIdEmpty = 5222;
	ErrChatMsgInfoEmpty = 5223;
	ErrChatNoShareChannel = 5224;
	ErrChatIllegalShareType = 5225;
	ErrChatIllegalHolderType = 5226;
	ErrChatNoSupportShareType = 5227;
	ErrChatShareTpeNoChatId = 5228;
	ErrChatShareNoFishRank = 5229;
	ErrChatLevelLimit = 5230;
	ErrChatNoFoundBlockListLimit = 5231;
	ErrTalentModTalentTagNotExist = 5301;
	ErrTextCheckForbidden = 5351;
	ErrTextCheckNoSceneType = 5352;
	ErrTextCheckIllegal = 5353;
	ErrTextCheckHttpError = 5354;
	ErrTextCheckTooManyItems = 5355;
	ErrConditionTimerOpen = 5401;
	ErrConditionOpenServer = 5402;
	ErrSkillDisable = 5700;
	ErrSkillIsCD = 5701;
	ErrSkillMaxPassiveCount = 5702;
	ErrSkillInit = 5703;
	ErrSkillInfo = 5704;
	ErrUseSkillFightResInsufficient = 5705;
	ErrUseSkillBuffNotEnough = 5706;
	ErrUseSkillItemInsufficient = 5707;
	ErrUseSkillAttrInsufficient = 5708;
	ErrUseSkillEnduranceInsufficient = 5709;
	ErrUseSkillStateChange = 5710;
	ErrUseSkillClientSkillUuid = 5711;
	ErrFightLogicConditionBlockInvalid = 5730;
	ErrFightLogicActionGroupInvalid = 5731;
	ErrFightLogicConditionNotMatch = 5732;
	ErrFightLogicRunDataInvalid = 5733;
	ErrSkillStageNotFind = 5734;
	ErrConditionCfgSize = 6000;
	ErrConditionDissatisfy = 6001;
	ErrConditionObjectIsNull = 6002;
	ErrConditionTypeNotFound = 6003;
	ErrConditionEntityDeath = 6004;
	ErrConditionUnionLevel = 6005;
	ErrConditionUnionMoney = 6006;
	ErrConditionNotMeet = 6007;
	ErrConditionNotInShapeShift = 6008;
	ErrSeasonAchievementNoExist = 6101;
	ErrSeasonAchievementNoFinish = 6102;
	ErrSeasonAchievementHasReceived = 6103;
	ErrSeasonAchievementPrevIdNoReceived = 6104;
	ErrSeasonAchievementPrevIdNoExist = 6105;
	ErrSeasonAchievementTargetConfigError = 6106;
	ErrSeasonRankHasMax = 6151;
	ErrSeasonRankHasReceived = 6152;
	ErrSeasonRankNoAchieve = 6153;
	ErrSeasonRankCurSeasonIdZero = 6154;
	ErrSeasonRankNoMeetCondition = 6155;
	ErrSeasonRankSeasonNoSame = 6156;
	ErrBattlePassBuyLevel = 6201;
	ErrBattlePassBuyMaterial = 6202;
	ErrBattlePassAwardGet = 6203;
	ErrBattlePassAwardNotUnlock = 6204;
	ErrBattlePassBuyWeekExpLimit = 6205;
	ErrBattlePassLevelError = 6206;
	ErrNoRefreshTimes = 6207;
	ErrTargetNotCompleted = 6208;
	ErrOnlinePeriodTooMore = 6251;
	ErrPersonalTagTooMore = 6252;
	ErrPersonalTagNotFound = 6253;
	ErrPersonalAvatarUnearned = 6254;
	ErrPersonalAvatarFrameUnearned = 6255;
	ErrPersonalCardStyleUnearned = 6256;
	ErrPersonalPhotoTooMore = 6257;
	ErrPersonalMedalUnearned = 6258;
	ErrPersonalTargetUnlock = 6259;
	ErrPersonalTargetAlreadyGet = 6260;
	ErrPersonalMedalInvalidSlot = 6261;
	ErrPersonalMedalDuplicateValue = 6262;
	ErrOnlinePeriodDuplicate = 6263;
	ErrPersonalTagDuplicate = 6264;
	ErrPersonalPhotoInvalidSlot = 6265;
	ErrPersonalPhotoDuplicateValue = 6266;
	ErrSeasonMedalNoMeetActiveCondition = 6301;
	ErrSeasonMedalNoMeetUpgradeCondition = 6302;
	ErrSeasonMedalActiveMeetNoEnough = 6303;
	ErrSeasonMedalUpgradeMeetNoEnough = 6304;
	ErrSeasonMedalIllegalNodeId = 6305;
	ErrSeasonMedalChooseNodeIdBeyondMax = 6306;
	ErrSeasonMedalHoleNoExist = 6307;
	ErrSeasonMedalHoleLock = 6308;
	ErrSeasonMedalNodeNoExist = 6309;
	ErrSeasonMedalHoleNoGet = 6310;
	ErrSeasonMedalMaxHoleLevel = 6311;
	ErrSeasonMedalCoreHoleLock = 6312;
	ErrSeasonMedalUpgradeMoneyNoEnough = 6313;
	ErrSeasonNoCoreHole = 6314;
	ErrSeasonNoNormalHole = 6315;
	ErrSeasonMedalNoUpgradeNormalHoleItem = 6316;
	ErrSceneLineNotExists = 6351;
	ErrSceneLineRefreshCd = 6352;
	ErrSceneLineNotSameScene = 6353;
	ErrSceneLineSameLine = 6354;
	ErrSceneLineInteracting = 6355;
	ErrSceneLineUserDead = 6356;
	ErrSceneLineFull = 6357;
	ErrSceneLineChangeCd = 6358;
	ErrSceneVersionRecycle = 6359;
	ErrSceneLineKick = 6360;
	ErrInstallSlotFailed = 6401;
	ErrUseSlotFailed = 6402;
	ErrUseSlotInCd = 6403;
	ErrInstatallSlotFailedInCombat = 6404;
	ErrSlotSkillUnLoad = 6405;
	ErrUseCfgSkillFailed = 6406;
	ErrResonanceNotExists = 6407;
	ErrResonanceUnLoad = 6408;
	ErrUseDodgeFailed = 6409;
	ErrUseFixedSkillFailed = 6410;
	ErrUseBlockedSkill = 6411;
	ErrInstallBlockedSkill = 6412;
	ErrExchangeNotFound = 6451;
	ErrExchangeNotEnough = 6452;
	ErrExchangeItemLimit = 6453;
	ErrExchangeStepRange = 6454;
	ErrExchangeItemFull = 6455;
	ErrExchangePackageFull = 6456;
	ErrExchangePriceItemNotFind = 6457;
	ErrExchangeBuyNumNotEnough = 6458;
	ErrExchangeBuyItemNotFound = 6459;
	ErrExchangeTakeFailDelayTime = 6460;
	ErrExchangeTakeFailSellNum = 6461;
	ErrExchangeTakeItemNotFound = 6462;
	ErrExchangeWithdrawNoMoney = 6463;
	ErrExchangeDepositNotEnough = 6464;
	ErrExchangeItemNotBindOrCooldownNotExpire = 6465;
	ErrExchangeInCd = 6466;
	ErrExchangeBuyCurrencyNoEnough = 6467;
	ErrExchangeItemDelayTimeOver = 6468;
	ErrExchangeItemIsNotWithdraw = 6469;
	ErrExchangeBuyItemLimit = 6470;
	ErrExchangeItemIsNotNoticeShopItem = 6471;
	ErrExchangeItemIsPreBuyAlready = 6472;
	ErrExchangeItemNotPublic = 6473;
	ErrExchangeSaleRankExist = 6474;
	ErrExchangeSaleItemFull = 6475;
	ErrExchangeSaleDiamondNotEnough = 6476;
	ErrExchangeSaleItemNotExists = 6477;
	ErrExchangeBuySaleCurrencyNoEnough = 6478;
	ErrExchangeDiamondNotEnough = 6479;
	ErrExchangeSaleTakeOffCd = 6480;
	ErrExchangeSaleRateInvalid = 6481;
	ErrExchangePreItemFull = 6482;
	ErrExchangeSaleNumInvalid = 6483;
	ErrExchangeCareItemAlready = 6484;
	ErrExchangePriceRange = 6485;
	ErrExchangeRequestLimit = 6486;
	ErrExchangeItemBanned = 6487;
	ErrExchangePriceNotLow = 6488;
	ErrExchangeItemNotFind = 6489;
	ErrExchangeItemExistMinPrice = 6490;
	ErrExchangeNoticeItemMin = 6491;
	ErrExchangePreBuyUserFull = 6492;
	ErrModHoleNotUnlock = 6501;
	ErrModNotExist = 6502;
	ErrModSimilarRepeated = 6503;
	ErrModTypeLimitExceeded = 6504;
	ErrModPartNotExist = 6505;
	ErrModPartEnhanceLimit = 6506;
	ErrModInUse = 6507;
	ErrModAlreadyInstalled = 6508;
	ErrModInitConfigNotExist = 6509;
	ErrModPartOverflow = 6510;
	ErrModCanNotLink = 6511;
	ErrFishingNotUseBait = 6551;
	ErrFishingRandomFailed = 6552;
	ErrFishingAlreadyGetFishItem = 6553;
	ErrFishingGetFishIdWrong = 6554;
	ErrFishingNotGet = 6555;
	ErrFishingNotResearchYet = 6556;
	ErrFishingNotUseRod = 6557;
	ErrFishingNoSeat = 6558;
	ErrFishingCantResearch = 6559;
	ErrFishDrawnLevelAward = 6560;
	ErrFishCannotDrawLevelAward = 6561;
	ErrFishDrawnNoLevelAward = 6562;
	ErrFreightNoRefreshGoods = 6601;
	ErrFreightBeyondMaxValue = 6602;
	ErrFreightDownMinValue = 6603;
	ErrFreightHasSetOff = 6604;
	ErrFreightNoSetOff = 6605;
	ErrFreightHasReward = 6606;
	ErrFreightIllegalGoodsId = 6607;
	ErrFreightItemNoEnough = 6608;
	ErrFreightNoUpSetOffTime = 6609;
	ErrFreightNoUpRewardTime = 6610;
	ErrFreightAutoSetOff = 6611;
	ErrTrialRoadAwardNotFinished = 6651;
	ErrTrialRoadAwardRoomGet = 6652;
	ErrNotCanRide = 6701;
	ErrCombatStateNotRide = 6702;
	ErrAlreadyRide = 6703;
	ErrRideNotEnough = 6704;
	ErrCreateVehicleActorFailed = 6705;
	ErrNotVehicleOwner = 6706;
	ErrVehicleHasController = 6707;
	ErrVehicleNoSeat = 6708;
	ErrVehicleHasSeat = 6709;
	ErrNotRideVehicle = 6710;
	ErrVehicleNotExits = 6711;
	ErrInvalidRidePropertyType = 6712;
	ErrRideApplyTargetUserNotExist = 6713;
	ErrRideConfigNotFind = 6714;
	ErrRideNotUnlock = 6715;
	ErrRideNotFind = 6716;
	ErrInvalidRideType = 6717;
	ErrRideApplyAlreadyExist = 6718;
	ErrRideApplyNotRideVehicle = 6719;
	ErrRideApplyVehicleNotSeat = 6720;
	ErrRideAlReadyRide = 6721;
	ErrRideApplyTargetTooFar = 6722;
	ErrRideNotTake = 6723;
	ErrRideInteracting = 6724;
	ErrShapeshiftNotRide = 6725;
	ErrFishingNotRide = 6726;
	ErrRideStateReject = 6727;
	ErrRideTypeNotSupport = 6728;
	ErrRideNotControl = 6729;
	ErrRideNotFunction = 6730;
	ErrRideSkinNotSupport = 6731;
	ErrRideSkinNotUnlock = 6732;
	ErrRideSkinDataAddFailed = 6733;
	ErrRideSkinNotSkin = 6734;
	ErrRideSkinAlreadyActivate = 6735;
	ErrWarehouseHas = 7000;
	ErrWarehouseNoHas = 7001;
	ErrWarehouseNoMem = 7002;
	ErrWarehouseNoPresident = 7003;
	ErrWarehouseNoHasItem = 7004;
	ErrWarehouseItemNoDeposit = 7005;
	ErrWarehouseGridPosNoExist = 7006;
	ErrWarehouseGridPosItemNoEnough = 7007;
	ErrWarehouseNoInviteSelf = 7008;
	ErrWarehouseInviteesHas = 7009;
	ErrWarehouseMemBeyondMax = 7010;
	ErrWarehouseGridBeyondMax = 7011;
	ErrWarehouseNoSelf = 7012;
	ErrWarehouseIsMem = 7013;
	ErrWarehouseNoExist = 7014;
	ErrWarehouseDepositBeyondMax = 7015;
	ErrWarehouseTakeOutBeyondMax = 7016;
	ErrWarehouseItemIdNotSame = 7017;
	ErrWarehouseParams = 7018;
	ErrWarehouseNoKickSelf = 7019;
	ErrWarehousePresidentNoExit = 7020;
	ErrGashaDrawCount = 7021;
	ErrGashaDrawLimit = 7022;
	ErrGashaInvalidWishId = 7023;
	EErGashaWishRepeated = 7026;
	EErGashaWishCountNoEnough = 7027;
	ErrWarehouseAuthority = 7028;
	ErrEquipCantDecompose = 7051;
	ErrEquipNotRecastRecord = 7052;
	ErrEquipOnCantUsedRecastConsume = 7053;
	ErrEquipWeaponNotEqualProfession = 7054;
	ErrEquipSlotRefineBlessNotFit = 7055;
	ErrEquipNotRecast = 7056;
	ErrEquipEnchantItemMismatch = 7057;
	ErrEquipEnchantAlreadyEnchanted = 7058;
	ErrEquipAnyItemMismatch = 7059;
	ErrEquipSlotRefineBlessNumTooMuch = 7060;
	ErrEquipNameGroupNoMatch = 7061;
	ErrEquipPerfectionNoMatch = 7062;
	ErrEquipNotBreak = 7063;
	ErrEquipPutOnIng = 7064;
	ErrUserIsMatching = 7101;
	ErrUserNotInMatching = 7102;
	ErrUseNotWaitReady = 7103;
	ErrDungeonCantMatch = 7104;
	ErrMatchQueueFull = 7105;
	ErrCommonAwardCantReceive = 7151;
	ErrCommonAwardHasReceived = 7152;
	ErrCraftEnergyNotEnough = 7201;
	ErrCraftEnergyFull = 7202;
	ErrRecommendPlayNotOpen = 7250;
	ErrWeeklyTowerNoStart = 7251;
	ErrWeeklyTowerHasEnd = 7252;
	ErrWeeklyNoMeetProcessAward = 7253;
	ErrWeeklyHasRewardProcessAward = 7254;
	ErrWeeklyNoLayerStageAward = 7255;
	ErrWeekOnlyCurSeasonAward = 7256;
	ErrWeeklyTowerCannotEnterLayer = 7257;
	ErrWeeklyTowerBoxHasOpen = 7258;
	ErrWeeklyTowerNoBox = 7259;
	ErrWeeklyTowerNoStageAward = 7260;
	ErrWeeklyTowerNoTowerDungeon = 7261;
	ErrFunctionNoAward = 7271;
	ErrFunctionHasDrawn = 7272;
	ErrTLogIllegalExportArea = 7281;
	ErrPayOrderFail = 7300;
	ErrPayCostNotEnough = 7301;
	ErrPayCantBuy = 7302;
	ErrPayCantExplore = 7303;
	ErrActivityNotFind = 7350;
	ErrActivityOffline = 7351;
	ErrActivityNotOpen = 7352;
	ErrActivityRewardNotFound = 7353;
	ErrActivityConditionNotFinish = 7354;
	ErrActivityAlreadyObtain = 7355;
	ErrActivityNotUnlock = 7356;
	ErrEmojiConfigError = 7401;
	ErrEmojiAlreadyUnlock = 7402;
	ErrEmojiUnlockItemError = 7403;
	ErrEmojiUnlockItemErrorItemNotEnough = 7404;
	ErrEmojiUnlock = 7405;
	ErrGlobalConditionNotFound = 7406;
	ErrGlobalConditionNotLuckyValue = 7407;
	ErrPathFindingCant = 7412;
	ErrPathFindingDataError = 7413;
	ErrPathFindingEndPosError = 7414;
	ErrPathFindingStartPosError = 7415;
	ErrPathFindingNoPath = 7416;
	ErrSignNotOpen = 7421;
	ErrSignNotSigned = 7422;
	ErrSignAlreadySigned = 7423;
	ErrSignTimeError = 7424;
	ErrTokenBucketLimit = 9998;
	ErrUnknown = 9999;
}

enum EItemBindFlag {
	ItemBindNone = 0;
	ItemNotBind = 1;
	ItemBindAll = 2;
}

enum EQuestStepStatus {
	QuestStepGoing = 0;
	QuestStepFinish = 1;
	QuestStepFail = 2;
}

enum EEntityType {
	EntErrType = 0;
	EntMonster = 1;
	EntNpc = 2;
	EntSceneObject = 3;
	EntZone = 5;
	EntBullet = 6;
	EntClientBullet = 7;
	EntPet = 8;
	EntChar = 10;
	EntDummy = 11;
	EntDrop = 12;
	EntField = 14;
	EntTrap = 15;
	EntCollection = 16;
	EntStaticObject = 18;
	EntVehicle = 19;
	EntToy = 20;
	EntCommunityHouse = 21;
	EntHouseItem = 22;
	EntCount = 23;
}

enum EDisappearType {
	EDisappearNormal = 0;
	EDisappearDead = 1;
	EDisappearDestroy = 2;
	EDisappearTransferLeave = 3;
	EDisappearTransferPassLineLeave = 4;
}